if ( GetLocale() == "koKR" ) then

Naut_localise = {

["NONESELECT"] = "선택하지 않음",
["SELECTTRANSPORT"] = "이동수단을 선택하세요",
["OPT_ZONEGUI"] = "이동수단을 포함하는 지역 변경의 경우 GUI창 표시",
["OPT_FACTION"] = "해당 진영의 이동수단만 표시",
["OPT_FACTION_DESC"] = "Shows only neutral and transports specific to your faction.",
["OPT_ZONE"] = "현재 지역의 이동수단만 표시",
["OPT_ZONE_DESC"] = "Shows only transports in your current zone.",
["OPT_ALIAS"] = "도착지의 다른이름 표시",
["OPT_ALIAS_DESC"] = "Displays destinations as city aliases instead of zone names (예. 티리스팔 숲 -> 언더시티).",
["SAVE"] = "저장",
["CLOSE"] = "닫기",
["HINT"] = "Click to cycle transport.|nAlt-Click to set up alarm",
["NEWVERSION"] = "There is a new version of Nauticus available! Please visit ui.worldofwar.net, curse-gaming.com or wowinterface.com.",

["DUROTAR"] = "듀로타",
["ORGRIMMAR"] = "오그리마",
["ORG"] = "오그",
["TIRISFAL"] = "티리스팔 숲",
["UNDERCITY"] = "언더시티",
["UC"] = "언더",
["STRANGLETHORN"] = "가시덤불 골짜기",
["GROMGOL"] = "그롬골 주둔지",
["GG"] = "가덤",
["BOOTYBAY"] = "무법항",
["BB"] = "무법",
["BARRENS"] = "불모의 땅",
["RATCHET"] = "톱니항",
["RA"] = "톱니",
["WETLANDS"] = "저습지",
["MENETHIL"] = "메네실 항구",
["MH"] = "메네실",
["DARKSHORE"] = "어둠의 해안",
["AUBERDINE"] = "아우버다인",
["AUB"] = "아우버",
["DUSTWALLOW"] = "먼지진흙 습지대",
["THERAMORE"] = "테라모어 섬",
["TH"] = "테라",
["TELDRASSIL"] = "텔드랏실",
["RUTTHERAN"] = "루테란 마을",
["RTV"] = "루테란",
["AZUREMYST"] = "Azuremyst Isle",
["EXODAR"] = "The Exodar",
["EXO"] = "Exo",
["SARDOR"] = "Sardor Isle",
["FEATHERMOON"] = "Feathermoon",
["FMS"] = "FMS",
["FERALAS"] = "Feralas",
["FORGOTTEN"] = "Forgotten Coast",
["FER"] = "Fer",

}

end
