
Naut_localise = {

["NONESELECT"] = "None Selected",
["SELECTTRANSPORT"] = "Select Transport",
["OPT_ZONEGUI"] = "Show GUI when zone change contains a transport",
["OPT_FACTION"] = "Show only transports for your faction",
["OPT_FACTION_DESC"] = "Shows only neutral and transports specific to your faction.",
["OPT_ZONE"] = "Show only transports in your current zone",
["OPT_ZONE_DESC"] = "Shows only transports in your current zone.",
["OPT_ALIAS"] = "Display using city aliases",
["OPT_ALIAS_DESC"] = "Displays destinations as city aliases instead of zone names (e.g. Undercity instead of Tirisfal Glades).",
["SAVE"] = "Save",
["CLOSE"] = "Close",
["HINT"] = "Click to cycle transport.|nAlt-Click to set up alarm",
["NEWVERSION"] = "There is a new version of Nauticus available! Please visit ui.worldofwar.net, curse-gaming.com or wowinterface.com.",

["DUROTAR"] = "Durotar",
["ORGRIMMAR"] = "Orgrimmar",
["ORG"] = "Org",
["TIRISFAL"] = "Tirisfal Glades",
["UNDERCITY"] = "Undercity",
["UC"] = "UC",
["STRANGLETHORN"] = "Stranglethorn Vale",
["GROMGOL"] = "Grom'gol",
["GG"] = "GG",
["BOOTYBAY"] = "Booty Bay",
["BB"] = "BB",
["BARRENS"] = "The Barrens",
["RATCHET"] = "Ratchet",
["RA"] = "Ra",
["WETLANDS"] = "Wetlands",
["MENETHIL"] = "Menethil Harbour",
["MH"] = "MH",
["DARKSHORE"] = "Darkshore",
["AUBERDINE"] = "Auberdine",
["AUB"] = "Aub",
["DUSTWALLOW"] = "Dustwallow Marsh",
["THERAMORE"] = "Theramore",
["TH"] = "Th",
["TELDRASSIL"] = "Teldrassil",
["RUTTHERAN"] = "Rut'Theran Village",
["RTV"] = "RTV",
["AZUREMYST"] = "Azuremyst Isle",
["EXODAR"] = "The Exodar",
["EXO"] = "Exo",
["SARDOR"] = "Sardor Isle",
["FEATHERMOON"] = "Feathermoon",
["FMS"] = "FMS",
["FERALAS"] = "Feralas",
["FORGOTTEN"] = "Forgotten Coast",
["FER"] = "Fer",

}
